### ISSUE TITLE
[Plugins]: Concept, Issues and Todo's

### ISSUE THREAD

**Issue by tannerlinsley** [nozzle/react-static#666]
The new plugin system is now under development and is already capable of a lot. This issue will be used to track the progress of converting each example to use as much of the plugin system as possible.

- [x] emotion - [react-static-plugin-emotion](https://github.com/nozzle/react-static-plugin-emotion)
- [x] styled-components [react-static-plugin-styled-components](https://github.com/nozzle/react-static-plugin-styled-components)
- [x] sass - [react-static-plugin-sass](https://github.com/nozzle/react-static-plugin-sass)
- [x] preact - [react-static-plugin-preact](https://github.com/nozzle/react-static-plugin-preact)
- [ ] typescript
- [ ] google-analytics
- [ ] material-ui
- [ ] styled-jsx
- [ ] gentics-mesh
- [ ] less-antdesign
- [ ] tailwindcss

**Comment by benedfit** [comment]
👍 for a Stylus example too

**Comment by tannerlinsley** [comment]
More added!

**Comment by danilobuerger** [comment]
@tannerlinsley I was looking into making the typescript plugin (it would be nice to have a repo for it) and discovered that some things which should be done by the plugin, can't be easily done at the moment:

```
  entry: path.join(__dirname, "src", "index.tsx"),
  extensions: [".js", ".jsx", ".ts", ".tsx"],
```

Those still have to be set in `static.config.js`. It would be nice if a plugin could also change the config.

**Comment by tannerlinsley** [comment]
Yes

**Comment by danilobuerger** [comment]
Then you should reopen the issue 🤗

**Comment by tannerlinsley** [comment]
Oh dang! No idea why or how I closed this...

**Comment by tannerlinsley** [comment]
The plugin system now allows options to be passed to plugins. And there are now sass and preact plugins. Join the movement!

**Comment by reachnana** [comment]
The react-static-plugin-sass plugin can't be found on npm...

**Comment by tannerlinsley** [comment]
It's not published yet. It's still being tested in the sass example's
plugin directory.

**Comment by tannerlinsley** [comment]
Not stale

**Comment by ilyanoskov** [comment]
@tannerlinsley could you please look into react-emotion plugin? It does not seem to work for me, the css gets applied with javascript, but the expectation is to apply it before?

**Comment by tannerlinsley** [comment]
@ilyanoskov The emotion plugin is functioning as expected in the emotion example on v6 branch.

**Comment by tannerlinsley** [comment]
I'll be looking into plugins that can also modify the config which should open up a lot of possibilities. Stay tuned!

**Comment by pdaddyo** [comment]
@tannerlinsley  How far along is the typescript plugin?  I couldn't get the`react-static` cli tool to work on my mac without installing the v6 beta, but our target project is using typescript.  Is this perhaps something I can help with?

**Comment by tannerlinsley** [comment]
@pdaddyo I would love your help to build the typescript plugin. The plugin docs in the v6 branch are up to date now, so I'd look at those.

I'm going to guess that there are some plugin hooks we still need to add to make the typescript plugin happen, but adding those is pretty easy.  Would you like to open a new PR for this or discuss more?

**Comment by DanWebb** [comment]
@tannerlinsley I had a go at implementing the GA plugin here https://github.com/DanWebb/react-static-plugin-google-analytics following the styled components example.

It's successfully inserting the standard GA code into `<head>` which tracks views on page load but I still got some work to do to make it page views between routes as explained here https://github.com/DanWebb/react-static-plugin-google-analytics

Do you think this is something that could possibly be achieved with the existing hooks or a hook is needed inside `<Router>` like I mention on the issue?

**Comment by tannerlinsley** [comment]
We probably need to add hooks to the client side for that, yes. Adding hooks to the client side is a different ball-game. We could take a page out of Gatsby's book on this one because we probably need to have server-side hooks and client side hooks use different import contexts.

What that really means is that you'll have to define your server-side hooks like normal, and define your client side hooks in a different file.

- Should we adopt a strict plugin api based on file structure like Gatbsy? eg. `react-static.server.js` and `react-static.client.js`?
- How and when should we import these plugins into the client-side bundle? Do we generate an import similar to react-static-routes? Do we make a webpack alias?

**Comment by Pixelatex** [comment]
Been thinking about a breadcrumb plugin that hooks into the routes we build. Not sure if this qualifies as a plugin or more of an extended feature of the routing. Any thoughts on this?

**Comment by Dragomir-Ivanov** [comment]
@Pixelatex In any case, please consider that one might **reload** the browser on a specific route, then you will loose any history information contained within the React application ( but the browser will still remember what was the previous route ). What I was thinking about this is to persists previous route in a URL query parameter. If you still are ready to loose the history in browser reload case, you might write a simple HOC receiving the history from `withRouter`, and then push that info in to a React Context spanning the whole application.

**Comment by Pixelatex** [comment]
@Dragomir-Ivanov We could write the breadcrumbs within the static json data we are rendering for each route. Since there is no need for this to be recalculated for every user.

**Comment by DanWebb** [comment]
@Pixelatex I think it's a good idea, it would make the client plugins more powerful if they could inject props in like how react routers [history](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/history.md) prop is passed in to page components now.

You could argue it'd be a good feature to add direct to React Static (I guess that's what you mean by "extended feature of the routing"?) but I think the idea fits the purpose of the plugins better, keeping the core React Static code base simple and optionally adding common extras people commonly need as plugins.

**Comment by Pixelatex** [comment]
@DanWebb I think stuff like this will be lightweight enough to not need to be a separate plugin if we provide them with the option to enable this so we don't render unneeded code.

Hmm.. when do we draw the line between what should be a feature and what shouldn't...

**Comment by DanWebb** [comment]
Isn't providing the option to enable exactly what a plugin is really though?

This is just my opinion but my current thinking is that the line get's drawn based on how essential the feature is. In this example, breadcrumbs aren't used or needed in many sites (including the 4 I've built in react static already) and really it's a nice to have rather than core functionality. In this case, it might be lightweight but add more lightweight features and it'll quickly add up.

**Comment by Pixelatex** [comment]
Not really. A plugin as I see it is something you download as a separate dependency while the feature I was describing is a part of the core package.

**Comment by DanWebb** [comment]
OK, but whether it's called a plugin, built-in plugin, setting, etc. It's an optional feature that can be enabled, right?

Would you agree whether it's built-in or not it should follow the same API so all the optional features can be enabled one way? If so, I think it makes sense all plugins originally start as standalone then maintainers can easily make the decision to get them moved into the core library later if it turns out a lot of people are using them just for convenience sake.

Client-side plugins will need to be built before this is possible so we will probably need to focus on that first 😅

**Comment by Pixelatex** [comment]
I do agree that making everything as standalone will make things easier to refactor/remove them. We can just bundle in certain plugins as standard then.

**Comment by tannerlinsley** [comment]
Yeah, I would say unless something that should be shipped in the code all the time, or is highly highly integrated with the core (plugin API's do not suffice), it should try and be a plugin. It's also not likely that we ship any plugins with the core install, even if they are soon merged into the same monorepo (like gatsby with lerna)

**Comment by tannerlinsley** [comment]
As for the problem above, I think we should track it in #790

**Comment by tannerlinsley** [comment]
FYI, I just added support for browser plugins: https://github.com/nozzle/react-static/commit/b1c2bebb491c347f7eb44db7687a51ca6a51521d

**Comment by sw-yx** [comment]
cleaned up some administrative comments which werent adding to discussion.

regarding plugin making, i'm new to all this. are plugins documented somewhere? how do i start?

**Comment by tannerlinsley** [comment]
The humble beginnings of the plugin documentation live here: https://github.com/nozzle/react-static/blob/v6/docs/plugins.md

There are no docs yet on implementing new hooks in the codebase, but at least for node hooks, you can easily replicate an existing hook. Browser hooks will be almost the same, but none are implemented yet. A description of how they could be implemented is here: b1c2beb

**Comment by tannerlinsley** [comment]
I think the next step (and probably group call) should focus on how we can plugin-ize as much of the react-static core as possible. Similar to gatsby, we should try and dogfood our own API as much as possible internally. This means we first need to swith to Lerna #797, move all of our plugins to monorepo packages, then really dig deep and discuss the internal points of react-static that we can turn into plugin hooks. Basically, the closer we can get react-static to look like a lifecycle runner (like react), the better. That way even "core" things like hot-reloading, route generation, etc are all abstracted into their own core plugins.  Thoughts?

**Comment by tannerlinsley** [comment]
Okay, the v6 branch is now a monorepo managed by lerna. I've moved all of the plugins built so far into the packages directory, too (along with a "Moved" notice on the old repo locations)

I haven't tested releases yet in lerna, but it's currently set to an "independent" mode (so all of the packages can have different versions) for now.

So for new plugins, just add a new directory in `/packages` and go for it!

**Comment by tannerlinsley** [comment]
Plugins just underwent an overhaul both internally and externally. You can check out the new docs here: https://github.com/nozzle/react-static/blob/v6/docs/plugins.md

Basically, there's now separate `node.api.js` and `browser.api.js` files, used for the different execution/import contexts.  The browser api still has no methods. There are a few more methods as well that I've added that also need to be documented.

**Comment by tannerlinsley** [comment]
You can also simply place either of those files in your project root and access the api at the project level. This is now going to be the de facto way of modifying the webpack config, too. (basically we just moved the webpack hook out of the static.config.js into the node.api.js file)

**Comment by sw-yx** [comment]
not stale

**Comment by tannerlinsley** [comment]
We'll keep this issue in the project for ongoing development, but as of now, plugins have been merged and released in v6, so going to close this issue.
